### ISSUE TITLE
How to access private repos

### ISSUE THREAD

**Issue by profucius** [cm-auto/gitweb-release-downloader#1]
I was able to successfully use your software to download the latest release from a public repo. How can I use it to access the latest release from a private repo? I have a github token and can access it via browser, but need to access it via your software. When I try, the software returns a "status code 404". Thanks

**Comment by cm-auto** [comment]
Currently it is not possible to supply authentication. I would need some time to study the documentations of the respective git APIs and implement the possibility of providing authentication.
However, I think it would be simpler and faster to implement the option to add custom http headers.
This way you could do something like this:
```command
grd download "github.com/owner/repo" "\\.xyz$" --header "Authorization: Bearer YOUR-TOKEN"
```
For more Information, see: https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28

Would this help in your use case?

**Comment by cm-auto** [comment]
Authentication is now possible by setting a custom http header, since 9745ae273f9074b66fdc4d8346d3bfb0a191615d (Version 1.1.0).

**Comment by profucius** [comment]
Thank you, I'll take a look at this! Can you tell me a bit more about how to write the custom http header for accessing private repos? I have the below command written for accessing a public repo just fine, what would I add to it for making it capable to access a private repo? I have a github token, would I use that?

`grd download --website-type github "cm-auto/gitweb-release-downloader" ".*amd64.exe$"`

**Comment by cm-auto** [comment]
It should be something like this:
```command
grd download --website-type github "cm-auto/gitweb-release-downloader" ".*amd64.exe$" --header "Authorization: Bearer YOUR-TOKEN"
```
Please keep in mind that github tokens can have different rights/scopes. You can find more information over here:
https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps

**Comment by profucius** [comment]
Thank you, so I gave that a try, and got a 404 error. Here is what I attempted:

`grd download --website-type github "debridmediamanager/zurg" ".*amd64.zip$" --prerelease --header "Authorization: Bearer PRIVATE"`

with result:

`Downloading "zurg-2024.11.27.0017-nightly-darwin-amd64.zip"
Error downloading file:
https://github.com/debridmediamanager/zurg/releases/download/2024.11.27.0028-nightly/zurg-2024.11.27.0017-nightly-darwin-amd64.zip: status code 404`

without including the --header token, it also gives a 404 but doesn't even find the file:

`HTTP request failed:
https://api.github.com/repos/debridmediamanager/zurg/releases: status code 404`

What I'm gathering from this is that the header is working, but maybe it doesn't work in combination with the --prerelease arg? If I remove --prerelease but keep the --header token, I get this:

`Could not find Pattern ".*amd64.zip$" in latest tag in releases of repository "debridmediamanager/zurg"`

This reinforces my thinking that the --header is working, but maybe a conflict with --prerelease?

Maybe worth mentioning: This repo does not contain an official release; It only contains prereleases.

Just to provide proof that the file does exist (the same in the log above):

![image](https://github.com/user-attachments/assets/71afc585-27ef-4d1d-9635-2d03401ec038)

**Comment by cm-auto** [comment]
Thank you for all the information. 👍️
I will reproduce this and investigate the problem.

**Comment by cm-auto** [comment]
The problem was that the field "browser_download_url" from the GitHub API was used and it seems like this url can't be used when trying to download from a private repository, even if a token is supplied.
In tag [1.1.1](https://github.com/cm-auto/gitweb-release-downloader/releases/tag/1.1.1) this problem has been fixed.

**Comment by profucius** [comment]
This worked perfectly! I appreciate this a lot, it will help my workflow so much.

**Comment by cm-auto** [comment]
That's great! I'm glad my software helps other people. 😄
